name: Cypress tests
on: push
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: '@cypress/github-action'
        with:
          build: npm run build
          start: npm start
          browser: chrome
          headed: true
          record: true
          spec: cypress/e2e/spec/**/*.js
          config: pageLoadTimeout=10000,baseUrl=http://localhost:8080