name: Main Workflow
on:
  workflow_dispatch
jobs:
  test:
    name: Cypress run
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build
      - name: Check running containers
        run: docker ps -a
      - name: Install dependencies
        run: npm install --package-lock-only
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
