name: Main Workflow
on:
  workflow_dispatch
jobs:
  test:
    name: Cypress run
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose -p reportportal up -d
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install --package-lock-only
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          wait-on: "http://localhost:8080"
          start: npx vite --host